title: Md Riyad Hossain
description: Web Developer
baseurl: "/resume/"
url: ""
resume_url: "resume.pdf"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
